// 학식 메뉴 데이터
const menuData = [
    {
        id: '1',
        name: '천원의 아침 (학생할인)',
        corner: '1번, 조식/석식',
        category: 'breakfast',
        nameEng: 'Breakfast for 1000 Won (Student Discount)',
        price: 6000,
        allergens: '계란(Eggs)',
        hasOptions: false,
        options: [],
        image: 'images/1.png',
        isFavorite: false
    },
    {
        id: '2',
        name: '돈육 짜글이',
        corner: '2번, 찌개/돌솥',
        category: 'stew',
        nameEng: 'Spicy Pork Stew',
        price: 5000,
        allergens: '계란(Eggs)',
        hasOptions: false,
        options: [],
        image: 'images/2.png',
        isFavorite: false
    },
    {
        id: '3',
        name: '추억의 도시락 덮밥',
        corner: '3번, 한식',
        category: 'korean',
        nameEng: 'Retro Lunchbox Rice Bowl',
        price: 4500,
        allergens: '계란(Eggs)',
        hasOptions: true,
        options: ['곱빼기'],
        image: 'images/3.png',
        isFavorite: false
    },
    {
        id: '4',
        name: '비빔밥',
        corner: '3번, 한식',
        category: 'korean',
        nameEng: 'Rice with a mix of vegetables',
        price: 4300,
        allergens: '없음(None)',
        hasOptions: false,
        options: [],
        image: 'images/4.png',
        isFavorite: false
    },
    {
        id: '5',
        name: '돈불고기 비빔밥',
        corner: '3번, 한식',
        category: 'korean',
        nameEng: 'Stir-fried Pork with Rice',
        price: 4800,
        allergens: '없음(None)',
        hasOptions: false,
        options: [],
        image: 'images/5.png',
        isFavorite: false
    },
    {
        id: '6',
        name: '쭈꾸미 비빔밥',
        corner: '3번, 한식',
        category: 'korean',
        nameEng: 'Webfoot Octopus Rice',
        price: 5800,
        allergens: '갑각류(Shellfish)',
        hasOptions: false,
        options: [],
        image: 'images/6.png',
        isFavorite: false
    },
    {
        id: '7',
        name: '등심돈까스+오므라이스',
        corner: '4번, 오므라이스',
        category: 'omurice',
        nameEng: 'Pork Cutlet with Omelet Rice',
        price: 6000,
        allergens: '계란(Eggs), 밀(Wheat)',
        hasOptions: false,
        options: [],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '8',
        name: '소시지 오므라이스',
        corner: '4번, 오므라이스',
        category: 'omurice',
        nameEng: 'Sausage Omelet',
        price: 5500,
        allergens: '계란(Eggs), 돼지고기(Pork)',
        hasOptions: false,
        options: [],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '9',
        name: '모듬카츠(치킨,돈등심,왕새우)',
        corner: '5번, 돈가스',
        category: 'cutlet',
        nameEng: 'Assorted Cutlets (Chicken, Pork, Shrimp)',
        price: 8000,
        allergens: '계란(Eggs), 갑각류(Shellfish)',
        hasOptions: false,
        options: [],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '10',
        name: '치킨까스',
        corner: '5번, 돈가스',
        category: 'cutlet',
        nameEng: 'Chicken Cutlet',
        price: 6000,
        allergens: '계란(Eggs)',
        hasOptions: false,
        options: [],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '11',
        name: '순살등심돈까스',
        corner: '5번, 돈가스',
        category: 'cutlet',
        nameEng: 'Boneless Pork Loin Cutlet',
        price: 6000,
        allergens: '계란(Eggs)',
        hasOptions: false,
        options: [],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '12',
        name: '치즈돈까스',
        corner: '5번, 돈가스',
        category: 'cutlet',
        nameEng: 'Cheese Pork Cutlet',
        price: 6000,
        allergens: '계란(Eggs), 유제품(Dairy)',
        hasOptions: false,
        options: [],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '13',
        name: '고구마치즈돈까스',
        corner: '5번, 돈가스',
        category: 'cutlet',
        nameEng: 'Sweet Potato Cheese Pork Cutlet',
        price: 7500,
        allergens: '계란(Eggs), 유제품(Dairy)',
        hasOptions: false,
        options: [],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '14',
        name: '생협김밥',
        corner: '6번, 분식',
        category: 'snack',
        nameEng: 'Korean Seaweed Rice Rolls',
        price: 3000,
        allergens: '없음(None)',
        hasOptions: false,
        options: [],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '15',
        name: '치즈김밥',
        corner: '6번, 분식',
        category: 'snack',
        nameEng: 'Korean Seaweed Rolls with Cheese',
        price: 3500,
        allergens: '유제품(Dairy)',
        hasOptions: false,
        options: [],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '16',
        name: '샐러드김밥',
        corner: '6번, 분식',
        category: 'snack',
        nameEng: 'Salad Gimbap',
        price: 3800,
        allergens: '계란(Eggs)',
        hasOptions: false,
        options: [],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '17',
        name: '참치마요김밥',
        corner: '6번, 분식',
        category: 'snack',
        nameEng: 'Tuna Mayo Gimbap',
        price: 4000,
        allergens: '계란(Eggs), 생선(Fish)',
        hasOptions: false,
        options: [],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '18',
        name: '유부우동',
        corner: '6번, 분식',
        category: 'snack',
        nameEng: 'Fried Bean Curd Udon',
        price: 3000,
        allergens: '대두(Soy)',
        hasOptions: true,
        options: ['곱빼기'],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '19',
        name: '김치우동',
        corner: '6번, 분식',
        category: 'snack',
        nameEng: 'Kimchi Udon',
        price: 3500,
        allergens: '없음(None)',
        hasOptions: true,
        options: ['곱빼기'],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '20',
        name: '꼬치우동',
        corner: '6번, 분식',
        category: 'snack',
        nameEng: 'Skewered Fish Cake Udon',
        price: 3800,
        allergens: '생선(Fish)',
        hasOptions: true,
        options: ['곱빼기'],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '21',
        name: '새우튀김 우동',
        corner: '6번, 분식',
        category: 'snack',
        nameEng: 'Shrimp Tempura Udon',
        price: 4000,
        allergens: '갑각류(Shellfish)',
        hasOptions: true,
        options: ['곱빼기'],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '22',
        name: '김밥우동세트',
        corner: '6번, 분식',
        category: 'snack',
        nameEng: 'Gimbap and Udon Set',
        price: 5500,
        allergens: '계란(Eggs)',
        hasOptions: true,
        options: ['곱빼기'],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '23',
        name: '목살샐러드',
        corner: '7번, 라면/샐러드',
        category: 'ramen',
        nameEng: 'Grilled Pork Neck Salad',
        price: 5500,
        allergens: '없음(None)',
        hasOptions: false,
        options: [],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '24',
        name: '계란라면',
        corner: '7번, 라면/샐러드',
        category: 'ramen',
        nameEng: 'Egg Ramen',
        price: 3000,
        allergens: '계란(Eggs)',
        hasOptions: true,
        options: ['공기밥', '삶은계란'],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '25',
        name: '치즈라면',
        corner: '7번, 라면/샐러드',
        category: 'ramen',
        nameEng: 'Cheese Ramen',
        price: 3500,
        allergens: '유제품(Dairy)',
        hasOptions: true,
        options: ['공기밥', '삶은계란'],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '26',
        name: '순두부열라면',
        corner: '7번, 라면/샐러드',
        category: 'ramen',
        nameEng: 'Spicy Soft Tofu Ramen',
        price: 3800,
        allergens: '대두(Soy)',
        hasOptions: true,
        options: ['공기밥', '삶은계란'],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '27',
        name: '라면정식',
        corner: '7번, 라면/샐러드',
        category: 'ramen',
        nameEng: 'Ramen Set',
        price: 3500,
        allergens: '없음(None)',
        hasOptions: true,
        options: ['공기밥', '삶은계란'],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '29',
        name: '라면김밥세트',
        corner: '7번, 라면/샐러드',
        category: 'ramen',
        nameEng: 'Ramen and Gimbap Set',
        price: 5500,
        allergens: '계란(Eggs)',
        hasOptions: true,
        options: ['공기밥', '삶은계란'],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '30',
        name: '짜계치',
        corner: '7번, 라면/샐러드',
        category: 'ramen',
        nameEng: 'Black Bean Sauce Ramen with Egg and Cheese',
        price: 3500,
        allergens: '계란(Eggs), 유제품(Dairy)',
        hasOptions: true,
        options: ['공기밥', '삶은계란'],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '31',
        name: '국물떡볶이',
        corner: '7번, 라면/샐러드',
        category: 'ramen',
        nameEng: 'Soup Tteokbokki',
        price: 3500,
        allergens: '없음(None)',
        hasOptions: true,
        options: ['공기밥', '삶은계란'],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '32',
        name: '삶은계란',
        corner: '7번, 라면/샐러드',
        category: 'ramen',
        nameEng: 'Boiled Eggs',
        price: 500,
        allergens: '계란(Eggs)',
        hasOptions: false,
        options: [],
        image: 'images/default.png',
        isFavorite: false
    },
    {
        id: '33',
        name: '공기밥',
        corner: '7번, 라면/샐러드',
        category: 'ramen',
        nameEng: 'Steamed Rice',
        price: 1000,
        allergens: '없음(None)',
        hasOptions: false,
        options: [],
        image: 'images/default.png',
        isFavorite: false
    }
];

// 메뉴 ID로 메뉴 가져오기
function getMenuById(id) {
    return menuData.find(menu => menu.id === id);
}

// 즐겨찾기된 메뉴만 가져오기
function getFavoriteMenus() {
    return menuData.filter(menu => menu.isFavorite);
}

// 카테고리별 메뉴 가져오기
function getMenuByCategory(category) {
    return menuData.filter(menu => menu.category === category);
}
